In [1]:
import pandas as pd
import numpy as np

In [8]:
data = pd.read_csv('data\cleaned_data.csv')
data.head()

,Unnamed: 0,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Time_Orderd,Time_Order_picked,Weather_conditions,...,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min),Day,Month,Year,restaurant_delivery_location_dist
0,0,36.0,4.2,30.327968,78.046106,30.397968,78.116106,21.916667,22.166667,Fog,...,Snack,motorcycle,3.0,No,Metropolitian,46,12,2,2022,10.271464
1,1,21.0,4.7,10.003064,76.307589,10.043064,76.347589,14.916667,15.083333,Stormy,...,Meal,motorcycle,1.0,No,Metropolitian,23,13,2,2022,6.229376
2,2,23.0,4.7,18.562450,73.916619,18.652450,74.006619,17.500000,17.666667,Sandstorms,...,Drinks,scooter,1.0,No,Metropolitian,21,4,3,2022,13.764306
3,3,34.0,4.3,30.899584,75.809346,30.919584,75.829346,9.333333,9.500000,Sandstorms,...,Buffet,motorcycle,0.0,No,Metropolitian,20,13,2,2022,2.927795
4,4,24.0,4.7,26.463504,80.372929,26.593504,80.502929,19.833333,20.083333,Fog,...,Snack,scooter,1.0,No,Metropolitian,41,14,2,2022,19.373484

In [9]:
# from eda we check that year and month has no significant importance in prdiction of time take so we will drop them and also this unnamed columns
data=data.drop(labels=['Unnamed: 0','Month','Year'],axis=1)
data.head()

,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Time_taken (min),Day,restaurant_delivery_location_dist
0,36.0,4.2,30.327968,78.046106,30.397968,78.116106,21.916667,22.166667,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46,12,10.271464
1,21.0,4.7,10.003064,76.307589,10.043064,76.347589,14.916667,15.083333,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23,13,6.229376
2,23.0,4.7,18.562450,73.916619,18.652450,74.006619,17.500000,17.666667,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21,4,13.764306
3,34.0,4.3,30.899584,75.809346,30.919584,75.829346,9.333333,9.500000,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20,13,2.927795
4,24.0,4.7,26.463504,80.372929,26.593504,80.502929,19.833333,20.083333,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41,14,19.373484

In [12]:
# segregating independent and depemdaent feature
## Independent and dependent features
X = data.drop(labels=['Time_taken (min)'],axis=1)
Y = data[['Time_taken (min)']]

In [13]:
# observing independent variables
X.head()

,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City,Day,restaurant_delivery_location_dist
0,36.0,4.2,30.327968,78.046106,30.397968,78.116106,21.916667,22.166667,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,12,10.271464
1,21.0,4.7,10.003064,76.307589,10.043064,76.347589,14.916667,15.083333,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,13,6.229376
2,23.0,4.7,18.562450,73.916619,18.652450,74.006619,17.500000,17.666667,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,4,13.764306
3,34.0,4.3,30.899584,75.809346,30.919584,75.829346,9.333333,9.500000,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,13,2.927795
4,24.0,4.7,26.463504,80.372929,26.593504,80.502929,19.833333,20.083333,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,14,19.373484

In [15]:
# observing dependable variable
Y.head()

   Time_taken (min)
0                46
1                23
2                21
3                20
4                41

In [18]:
# Define which columns should be one hot-encoded and which should be scaled
categorical_cols = X.select_dtypes(include='object').columns
numerical_cols = X.select_dtypes(exclude='object').columns

print('categorical features: \n',categorical_cols)
print('\nnumerical features: \n',numerical_cols)

categorical features:
 Index(['Weather_conditions', 'Road_traffic_density', 'Type_of_order',
       'Type_of_vehicle', 'Festival', 'City'],
      dtype='object')

numerical features:
 Index(['Delivery_person_Age', 'Delivery_person_Ratings', 'Restaurant_latitude',
       'Restaurant_longitude', 'Delivery_location_latitude',
       'Delivery_location_longitude', 'Time_Orderd', 'Time_Order_picked',
       'Vehicle_condition', 'multiple_deliveries', 'Day',
       'restaurant_delivery_location_dist'],
      dtype='object')

### Creating the training pielines

In [19]:
from sklearn.impute import SimpleImputer ## HAndling Missing Values
from sklearn.preprocessing import StandardScaler # HAndling Feature Scaling
from sklearn.preprocessing import OneHotEncoder # one hot encoding
## pipelines
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [23]:
## Numerical Pipeline
num_pipeline=Pipeline(
    steps=[
    ('imputer',SimpleImputer(strategy='median')),
    ('scaler',StandardScaler())

    ]

)

# Categorigal Pipeline
cat_pipeline=Pipeline(
    steps=[
    ('imputer',SimpleImputer(strategy='most_frequent')),
    ('one_hot_encoder',OneHotEncoder()),
    ]

)

preprocessor=ColumnTransformer([
('num_pipeline',num_pipeline,numerical_cols),
('cat_pipeline',cat_pipeline,categorical_cols)
])

In [21]:
## Train test split

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.30,random_state=30)

In [24]:
# placing the transformed data into a data frame
X_train=pd.DataFrame(preprocessor.fit_transform(X_train),columns=preprocessor.get_feature_names_out())
X_test=pd.DataFrame(preprocessor.transform(X_test),columns=preprocessor.get_feature_names_out())

In [25]:
X_train.head()

,num_pipeline__Delivery_person_Age,num_pipeline__Delivery_person_Ratings,num_pipeline__Restaurant_latitude,num_pipeline__Restaurant_longitude,num_pipeline__Delivery_location_latitude,num_pipeline__Delivery_location_longitude,num_pipeline__Time_Orderd,num_pipeline__Time_Order_picked,num_pipeline__Vehicle_condition,num_pipeline__multiple_deliveries,...,cat_pipeline__Type_of_order_Snack,cat_pipeline__Type_of_vehicle_bicycle,cat_pipeline__Type_of_vehicle_electric_scooter,cat_pipeline__Type_of_vehicle_motorcycle,cat_pipeline__Type_of_vehicle_scooter,cat_pipeline__Festival_No,cat_pipeline__Festival_Yes,cat_pipeline__City_Metropolitian,cat_pipeline__City_Semi-Urban,cat_pipeline__City_Urban
0,1.124025,-1.623440,0.647373,0.131167,0.669961,0.116679,0.782231,0.772747,-1.223528,-1.318236,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
1,-0.106505,-3.143059,0.647397,0.131248,0.668629,0.116295,0.705693,0.684568,-1.223528,3.943714,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
2,0.245075,0.504025,1.156141,0.443938,1.228657,0.452410,-0.888856,-0.877455,1.160323,0.435747,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
3,0.596655,-1.319517,-0.226656,0.165206,-0.293358,0.156297,0.412296,0.420032,1.160323,0.435747,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
4,0.772445,-1.623440,0.258322,0.116402,0.230746,0.098366,-1.195009,-2.470970,-1.223528,0.435747,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0

## Model traning

In [26]:
## Model Training

from sklearn.linear_model import LinearRegression,Lasso,Ridge,ElasticNet
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

In [27]:
regression=LinearRegression()
regression.fit(X_train,y_train)

LinearRegression()

In [28]:
regression.coef_

array([[ 2.26735104e+00, -2.39027060e+00,  8.61869378e-02,
        -2.40308923e-01, -2.47297501e-02,  2.11219395e-01,
         3.33323820e-01,  3.18386307e-01, -1.72763625e+00,
         1.83204859e+00,  7.83450655e-02,  1.00237989e-01,
         6.58722882e+12,  6.58722882e+12,  6.58722882e+12,
         6.58722882e+12,  6.58722882e+12,  6.58722882e+12,
         7.09036070e+11,  7.09036070e+11,  7.09036070e+11,
         7.09036070e+11,  2.71800837e+13,  2.71800837e+13,
         2.71800837e+13,  2.71800837e+13,  7.43268664e+11,
         7.43268664e+11,  7.43268664e+11,  7.43268664e+11,
         1.67073482e+12,  1.67073482e+12, -3.54190841e+11,
        -3.54190841e+11, -3.54190841e+11]])

In [29]:
regression.intercept_

array([-3.65361612e+13])

In [35]:
# creating a function to evalute the models with using multiple metric

import numpy as np
from typing import Tuple

def evaluate_model(true: np.ndarray, predicted: np.ndarray) -> Tuple[float, float, float]:
    """
    Calculates several metrics to evaluate the performance of a regression model.

    Parameters:
    true (array-like): The true values of the target variable.
    predicted (array-like): The predicted values of the target variable.

    Returns:
    tuple: A tuple containing the mean absolute error (MAE), root mean squared error (RMSE),
           and R-squared (R2) value for the model's performance.
    """
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mean_squared_error(true, predicted))
    r2_square = r2_score(true, predicted)
    return mae, rmse, r2_square

In [31]:
## Train multiple models

models={
    'LinearRegression':LinearRegression(),
    'Lasso':Lasso(),
    'Ridge':Ridge(),
    'Elasticnet':ElasticNet()
}

trained_model_list=[]
model_list=[]
r2_list=[]

for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)

    #Make Predictions
    y_pred=model.predict(X_test)

    mae, rmse, r2_square=evaluate_model(y_test,y_pred)

    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

    print('Model Training Performance')
    print("RMSE:",rmse)
    print("MAE:",mae)
    print("R2 score",r2_square*100)

    r2_list.append(r2_square)
    
    print('='*35)
    print('\n')

LinearRegression
Model Training Performance
RMSE: 6.266216602615751
MAE: 4.954585130886224
R2 score 54.603724300291304
===================================


Lasso
Model Training Performance
RMSE: 7.499541778506498
MAE: 5.934370046026073
R2 score 34.97522221991508
===================================


Ridge
Model Training Performance
RMSE: 6.265452800896429
MAE: 4.9536435446565905
R2 score 54.61479051213883
===================================


Elasticnet
Model Training Performance
RMSE: 7.589801417882317
MAE: 6.045611290173301
R2 score 33.40061097211506
===================================

In [33]:
# printing inthe interrcept and coeffiecints of all models

for model in models:
    print(f'{model} coefficients:\n {models[model].coef_}\n')
    print(f'{model} intercept:\n {models[model].intercept_}\n')

LinearRegression coefficients:
 [[ 2.26735104e+00 -2.39027060e+00  8.61869378e-02 -2.40308923e-01
  -2.47297501e-02  2.11219395e-01  3.33323820e-01  3.18386307e-01
  -1.72763625e+00  1.83204859e+00  7.83450655e-02  1.00237989e-01
   6.58722882e+12  6.58722882e+12  6.58722882e+12  6.58722882e+12
   6.58722882e+12  6.58722882e+12  7.09036070e+11  7.09036070e+11
   7.09036070e+11  7.09036070e+11  2.71800837e+13  2.71800837e+13
   2.71800837e+13  2.71800837e+13  7.43268664e+11  7.43268664e+11
   7.43268664e+11  7.43268664e+11  1.67073482e+12  1.67073482e+12
  -3.54190841e+11 -3.54190841e+11 -3.54190841e+11]]

LinearRegression intercept:
 [-3.65361612e+13]

Lasso coefficients:
 [ 1.44306042 -1.75086315  0.         -0.          0.          0.
  0.          0.         -0.95135095  1.96112123  0.          0.
  0.          0.         -0.         -0.         -0.         -0.
  0.          0.50856519 -2.15046335 -0.         -0.         -0.
  0.          0.          0.         -0.          0.         -0.
 -0.          0.          0.          0.         -0.        ]

Lasso intercept:
 [26.91773048]

Ridge coefficients:
 [[ 2.26739667 -2.39317878  0.111057   -0.1804676  -0.0534056   0.16711383
   0.33508763  0.32737422 -1.73283735  1.82811966  0.0771601   0.13142244
   2.34187912  2.59455582 -0.42928653 -0.35820364 -3.87147165 -0.27747312
   1.09269718  3.24424622 -4.56992466  0.23298125 -0.03509203 -0.07574974
   0.04898244  0.06185934  1.381998   -0.01784864 -0.4165229  -0.94762646
  -5.15708211  5.15708211 -2.82450494  7.69554181 -4.87103687]]

Ridge intercept:
 [35.44256403]

Elasticnet coefficients:
 [ 1.32804688 -1.50908598  0.         -0.          0.          0.
  0.16616882  0.15231674 -0.99787772  1.66786046  0.          0.
  0.          0.         -0.         -0.         -0.25569496 -0.
  0.          0.97104559 -1.31045913  0.         -0.         -0.
  0.          0.          0.         -0.          0.         -0.
 -0.          0.          0.          0.         -0.10237522]

Elasticnet intercept:
 [26.54119203]